### ISSUE TITLE
no license specified (just a copyright notice)

### ISSUE THREAD

**Issue by bymerej** [openexchangerates/money.js#2]
I can't find the license for this code, just a copyright notice?

Please add one somewhere. (ideally it should be in /LICENSE and also at least referenced from the readme and any place where you already have copyright notices)

Thanks!

**Comment by wjcrowcroft** [comment]
Good point, will add license info soon. 

Shouldn't stop you from using it, though, unless you were planning to change the name and sell it for profit - which would be extremely uncool!

**Comment by bymerej** [comment]
Hard to imagine a lawyer (or a jury) would agree with that. But IANAL.
e.g. if you sued me for shipping a tarball with your library (as is; missing a license) in it. (same name but part of a larger project. e.g. zencart or a clone of it)

In any case, this is a problem (and a blocker not something that can be fixed later) for a large swath of potential projects. (I don't have any planned uses at the moment so not an immediate issue for me) Any software which relies on this library as it's currently published would [fail the test for inclusion in Debian's "main" archive](http://www.debian.org/doc/debian-policy/ch-archive.html#s-main). (unless I missed something when searching for a license but your comment makes me think I didn't)

Anyway, I look forward to seeing which license you choose. Thanks!

**Comment by wjcrowcroft** [comment]
I'll probably just go with whatever enables the most people to use it without hassle. Any ideas?

**Comment by bymerej** [comment]
I'd say any of BSD (although there's multiple styles and I don't have them straight), AGPL, and GPL. I'd probably go with AGPL myself.

It depends what you're looking for. e.g. do you want people to be able to make derivatives and sell the derivatives without releasing the source for others to use under the same terms? or without releasing the source at all?

Also remember you don't have to pick just one. If all of the code there was originally written by you and you retain all of the rights to it (wasn't work for hire or signed away to someone) then you can release it under multiple licenses (even if they're incompatible with each other) and let the user choose which one they want to use it under. You can also offer companies custom terms for licensing if none of the options it's already published under work for them. All of this paragraph goes out the window and doesn't apply once you start accepting contributions from other people.

I just found http://home.ccil.org/~cowan/floss/ which may help you think about licensing criteria but I can't vouch for it's accuracy.

If you come up with some criteria for what you want in a license I'm happy to help you find one that fits your needs.

**Comment by wjcrowcroft** [comment]
Thanks for the advice, apologies for the silence the past month. Think I'm leaning toward LGPL because it's less restrictive than GPL but has the same freedoms. Just researching it this weekend.

**Comment by wjcrowcroft** [comment]
Licensed under MIT now. Saves me reading through another damn explanation of various different licenses, and hopefully everyone can do what they like with it!
