### ISSUE TITLE
Incorrect Open Exchange Rates

### ISSUE THREAD

**Issue by hendrasan** [openexchangerates/money.js#3]
Where do you get the rates from? because I checked the latest rates json, and 1 USD is stated as 7 thousands something IDR, while I'm sure IDR is Indonesian Rupiahs and 1 USD is surely not 7 thousands something :) It should be 8 thousands something, close to 9,000. I checked IDR with GBP is incorrect too, so I'm sure something's wrong with the data.

**Comment by wjcrowcroft** [comment]
Thanks for flagging this up. 

It's early days and as with all open source projects there will be hurdles!

edit: just realised you made this issue on the money.js repository, which is a standalone JS library that operates independently from the exchange rates data. Closing for that reason, but feel free to open the same ticket on the Open Exchange Rates repo, which is where the demo page gets the rates from.
